### ISSUE TITLE
Upload Cropped Image to Server?

### ISSUE THREAD

**Issue by coommark** [AllanBishop/angular-img-cropper#1]
Awesome! Other than the super beautiful crop controls, I love the fact that this tool does only one thing!It is so difficult to find an angular cropper that isn't burdened with rotate, skew, etc etc. Thanks for this.

Please do you have a small sample to show how to upload the cropped image to server? Say Nodejs? Just a little pointer might do, because I am pitching my tent here!

Oh and I did evaluate about a dozen other solutions, but this shines!

**Comment by AllanBishop** [comment]
Thanks! Glad you like it. I don't have a NodeJS example right now, but I do have a PHP example ripped form one of my projects if that helps in the mean time.

<pre>
<code>
$scope.selectCroppedPhoto = function()
{
	var croppedImage = {};
	croppedImage.dataUrl = $scope.cropper.croppedImage;
	croppedImage.name = $scope.generateUniqueName();
	$scope.cropper.sourceImage = null;
	$scope.listForm.croppedImages.push(croppedImage);
}

$scope.submit = function()
{
	//Unfortunately can't upload all at once so need to upload one by one
	for (var i = 0; i < $scope.listForm.croppedImages.length; ++i) 
	{
		$upload.upload({
			url: 'http://127.0.0.1/projects/list',
			headers: {'Content-Type': "multipart/form-data"},
			method: 'POST',
			data:  {image:$scope.listForm.croppedImages[i]}
		}).progress(function(evt) 
		{

		}).success(function(data, status, headers, config) 
		{
			//is last image
			if(i==$scope.listForm.croppedImages.length-1)
			{
				//TODO redirect
			}
		});
	}
}

$scope.seed = 0;
$scope.generateUniqueName = function()
{
    $scope.seed++;
	return $scope.seed;
}
</code>
</pre>

**Comment by coommark** [comment]
Thank you!  This code will do. Your cropper is going to hit it. I will drop a NodeJs sample here shortly, for those of the nodejs community. Been following the threads, cool!
