### ISSUE TITLE
cropBounds model update extremely often

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#10]
Hi there, 
Still playing with your component. And I realized that cropBounds model binding is updated (I think) way too often. Especially when you simply hover your cursor on top of the canvas, the property is constantly updated which I think is not the intended behaviour.
Am I right ?

**Comment by AllanBishop** [comment]
Yep you are right! I have now fixed this so it only updates when the corners get dragged or when the area bounds is moved.

**Comment by HadrienPierart** [comment]
Great !
Can we use this property to change the bounds dynamically from the parent controller for instance ?
I just tried but it doesnt seem to change anything. I'm trying to set a min width and height on crop size through using cropBounds size as watch.
