### ISSUE TITLE
Crop area bug

### ISSUE THREAD

**Issue by lukaszwyzykowski** [AllanBishop/angular-img-cropper#17]
Hi, i found a bug with crop area in specific situation:
Please change canvas attributes to: crop-width="1024" crop-height="1024" and load this image:
![bug_image](https://cloud.githubusercontent.com/assets/7814856/8356393/3dd274e2-1b55-11e5-9370-95de7395f081.png)

Any ideas how to fix that?

Screenshot:
![zrzut ekranu 2015-06-25 o 16 15 59](https://cloud.githubusercontent.com/assets/7814856/8356432/8b68ddfe-1b55-11e5-84e4-f231fa8bb3dd.png)

**Comment by AllanBishop** [comment]
Ah yeah. Seems any square crop shape is breaking. I will look into it.

**Comment by AllanBishop** [comment]
Ok it turned out to be when a square image and square crop shape were being used. Should now be fixed!
