### ISSUE TITLE
Wrong crop coordinates calculated for crop

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#2]
Hi there,

I've been trying on your nice module for a few days now and I can't seem to get the correct coordinates of the crop rectangle/square. Somehow, the top left corner is always 1 px short and the witdh/height are around 2 or 3 px short.
I'm guessing here : I'd say the crop border is not included in the crop size/coordinates. Which for me is a mistake, because if you want to cut out the whole image, you cannot...

A nice thing to do would also be to publish these coordinates and not only the cropped image (that's actually what I did to figure what was wrong with the cropped image).

**Comment by AllanBishop** [comment]
Hi,

I have added a new parameter for the directive which allows a model to be automatically updated with the current crop area in relation to the image. I have updated the documentation and demo accordingly. Top left corner is showing 0 for me on both Chrome and Firefox.

**Comment by HadrienPierart** [comment]
Indeed, that's better, but wouldn't you rather publish the crop corners position instead of the bounds ?
In any case, I have check on the demo and the cropped bounds that are published are calculated on the size of the image displayed in the canvas, and not based on the source image. Thus, as a user standpoint, as we don't know the ratio applied to scale down the image into the canvas, it's almost impossible to calculate the correct bounds positions...

About the position of the corners, maybe it's something I did on my branch that messed up the 0. I'll check.

**Comment by AllanBishop** [comment]
I feel bounds is neater and has all the data required to display the corners. A data structure with the corners contains too much redundant values for my liking. Yes, good point about the values of the bounds being based on the scaled down image. I have now updated this to be based on the original image dimensions.

**Comment by HadrienPierart** [comment]
Great. I'll try that a bit later and keep you posted. Thanks !
