### ISSUE TITLE
Problem with bounds

### ISSUE THREAD

**Issue by Autushka** [AllanBishop/angular-img-cropper#21]
Hello,

If I have my bounds values persisted somewhere and want to display a source image and a cropped one with predefined bounds it seems that bounds are overwritten with default values I need to crop the file again.

**Comment by zvictor** [comment]
I am trying to work on that one. There is a function at `ImageCropper.prototype.setBounds` that should be able to do the job, but there is no call for it on the code and its implementation seems to be incomplete. I made it work somehow, but the crop area still miss offset and it is not draggable.

@AllanBishop do you have any input to help us here?

**Comment by zvictor** [comment]
#27 tries to solve the problem, but I could not get rid of an annoying horizontal displacement of the crop area =/
