### ISSUE TITLE
Is it possible to limit the size of the cropping area ?

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#3]
I dont think I have seen that in the params of the directive but I would be great to be able to limit the options regarding the cropping area. For instance, I would like to be able to say : 
My cropping tool must be a squate, not a rectangle.
My cropping tool cannot have a smaller width and height than 600px

It would be great for when you want to send picture of at least a certain size or format.

**Comment by AllanBishop** [comment]
You can ensure that the cropping tool is square by setting the crop-width and crop-height to the same number and ensuring keep-aspect is true.

The crop-width and crop-height will ensure the image is of a certain size but there is no feature for allowing a variety of sizes with a threshold. 

My main goal for the cropping tool was to ensure images on the server would be one particular size that the user could then crop for. Certainly possible to add that feature but I want to avoid cluttering the tool with too many parameters.

**Comment by HadrienPierart** [comment]
ok good to know. Thanks for the answer. I'll see to do it on my own then. Maybe with another directive working in conjunction with yours.

**Comment by AllanBishop** [comment]
No problem. Sounds like a good plan.
