### ISSUE TITLE
Consider tagging a version to help your lib grow ?

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#4]
Hi there,

Me again, I really like your plugin, so I'm coming with a few ideas now and then :D
Have you considered tagging a first version in git ? That would simplify the integration in a bower.json file and make it easier to install, thus improving the potential popularity of your solution !

**Comment by AllanBishop** [comment]
Thanks :) Please do. Indeed on your suggestion I have published a release.
