### ISSUE TITLE
Adding canvas removes cursor:pointer

### ISSUE THREAD

**Issue by Nitad** [AllanBishop/angular-img-cropper#5]
Or rather, adding 'image-cropper' to the canvas element, not happening if i add it to a div. 
Also, the entire page is one big accordion, if that could contribute to the issue.
Any ideas?

**Comment by AllanBishop** [comment]
I have fixed #6 Does this resolve this issue for you as well?

**Comment by Nitad** [comment]
yes but the issue with el.style.cursor = 'nwse-resize';  gets called when im hovering over a random p-element nowhere near the canvas. Actually all the resizes

**Comment by Nitad** [comment]
i have 2 canvases, one works, the other one dont have any cursor-changes when cropping, instead the cursor-changes happen on another part of the page on a fixed element.

**Comment by AllanBishop** [comment]
Ah yes I see, I have created a test with two image croppers with two canvases and can see only one of them has the cursor-changes. I will investigate this.

**Comment by Nitad** [comment]
Very cool, thanks =)

**Comment by AllanBishop** [comment]
I have created a new service that injects into the directive allowing intelligent decision making when displaying the cursors on a page with multiple directives. I tested it with two canvas images and it seemed to work well. Let me know how you go with it and if it is good will mark it as a release.

**Comment by Nitad** [comment]
That helped with the changes to the cursor on the second canvas, but i still get cursor changes on the element that is next to the canvas with properties float:left and position:fixed.

**Comment by Nitad** [comment]
![image](https://cloud.githubusercontent.com/assets/5262593/7726904/a7df791e-ff05-11e4-8919-983bf3235af4.png)

**Comment by Nitad** [comment]
![image](https://cloud.githubusercontent.com/assets/5262593/7726917/ba9aeafc-ff05-11e4-91d1-475d5c2bed0d.png)

**Comment by AllanBishop** [comment]
Updated the code to set the cursor style at the root html element. This should fix your issue.

**Comment by Nitad** [comment]
Perfect! Thanks

**Comment by Nitad** [comment]
Although, now the mouse wont change when hovering the crop area

**Comment by AllanBishop** [comment]
Hmm I am having trouble replicating this issue. So far with the previous problems I have created two canvases (with directive attached) and have set the styles so that they floated right and another div was floating left with a fixed position. However this setup is working fine for me with hovering functioning correctly. Is there anything else on your page that would be setup differently to my test case?

**Comment by Nitad** [comment]
Sorry, my bad. cursor: auto rule in foundation.css that borked it. Thanks!

**Comment by Nitad** [comment]
If you have cursor:auto or default on the body for example, it seems to break it.

**Comment by Nitad** [comment]
The issue with the random cursor-changes is back. However, they disappear after i chose a picture for the canvas. Only using one canvas. Been adding alot of css-changes which may have caused it, im am unsure to which changes made the behavior return.

**Comment by AllanBishop** [comment]
Are you setting cursor in your css anywhere? Also, while investigating this I found a bug where the cursor logic was happening before an image had loaded. I have fixed this and maybe this will help?

**Comment by Nitad** [comment]
Thanks again! That did the trick it seems :D
