### ISSUE TITLE
Cursor initial everywhere

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#6]
One more ;)

I've spotted that my DOM was suddenly clogged with cursor: initial style attributes and I tracked the culprit down to this line :

    // In drawCursors function
    el.style.cursor = 'initial';

I think something is wrong with the way you select elements because you're putting cursor: initial on EVERY elements in the page (And it goes without saying that it's bad !)

Please do fix it :)

**Comment by Nitad** [comment]
el.style.cursor = 'nwse-resize'; also gets called when im hovering over a random p-element nowhere near the canvas

**Comment by HadrienPierart** [comment]
yep that's what I was trying to say by on EVERY element :p

**Comment by Nitad** [comment]
initial, you never mentioned nwse-resize :/

**Comment by HadrienPierart** [comment]
true :D

**Comment by AllanBishop** [comment]
Ah yes, whoops! I have now changed this so only the body has a cursor style added/changed.
