### ISSUE TITLE
Uploading smaller picture than canvas distorts cropped picture

### ISSUE THREAD

**Issue by Nitad** [AllanBishop/angular-img-cropper#7]
If you upload a smaller picture than the canvas, but still bigger than the cropping you want, the cropped picture gets distorted.

**Comment by Nitad** [comment]
![image](https://cloud.githubusercontent.com/assets/5262593/7748484/4e8dbe82-ffc5-11e4-9f8c-48398a943626.png)
canvas:300x300, crop 100x100, picture 164x162

**Comment by AllanBishop** [comment]
This is now fixed.
