### ISSUE TITLE
Get request for image on every click

### ISSUE THREAD

**Issue by Nitad** [AllanBishop/angular-img-cropper#8]
![image](https://cloud.githubusercontent.com/assets/5262593/7755377/e030886e-fff3-11e4-8bb1-d2cf569e6cc7.png)
Anytime i click anywhere on the website the directive does a get-request to my cropped image.

**Comment by AllanBishop** [comment]
This is now fixed so this only occurs when you are dragging the cropping tool and not every mouse/touch up.
