### ISSUE TITLE
img-cropper-fileread not only on input element.

### ISSUE THREAD

**Issue by Nitad** [AllanBishop/angular-img-cropper#9]
Not really a bug or anything but since input elements are a bitch to style it would be nice if you could put img-cropper-fileread and image directives on buttons and/or a-elemenets aswell, thanks =)

**Comment by AllanBishop** [comment]
Did you mean so it could work similar to this? http://stackoverflow.com/questions/6463439/how-to-open-a-file-browse-dialog-using-javascript

**Comment by Nitad** [comment]
Exactly =)

**Comment by AllanBishop** [comment]
Finally got around to this. It is a little more fiddly to set up than using an input element so I have created a wiki page for it. [Load file with ng-click tutorial](https://github.com/AllanBishop/angular-img-cropper/wiki/Load-image-via-ng-click-tutorial)

**Comment by Nitad** [comment]
Nice work =)
